### PR TITLE
User interface of the tic tac toe project

### PR DESCRIPTION
**Pull request by Addis-Belete**
This is the second milestone of the tic tac toe project. it has the interface of the game which is done in the main file as requested.

### CODE REVIEW

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUIRED :writing_hand:
Hello team @Addis0943 and @Shaher-11, a great effort so far in this milestone. 👏🏾 

#### To Highlight

- [x] Good job on following the correct GitHub flow ✔️  
- [x] Your commit messages are well written in the present tense ✔️ 
- [x] Your PR description is short and clear ✔️ 

#### To Improve

- You have done a nice job implementing the user interface, however, let's make it even better by implementing some features

- [x] Game informs the player if the selected move is invalid (without computing what an invalid move is). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/invalid_move.png)
- [x] Game displays board after the player move (without computing which spots on the board are taken). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/player_turn.png)
* [x] Game informs player if the selected move is a draw move (without computing draw). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_tie.png)
* [x] Game repeats all actions for the next player's move. [Example gif](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_flow_example.gif)

##### Implementation details

* [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [x] Inside the loop, the student should call actions repeated for each move
* [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name  (@mimipeshy) and I will be glad to help_
Regards
Peris Ndanu

**Comment by Addis-Belete** [comment]
we did the required changes for the user_interface milestone.

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUIRED :writing_hand:
Hello team @Addis0943 and @Shaher-11, a great effort so far in this milestone. 👏🏾 

#### To Improve
- [x] Your game goes into an infinite loop after declaring a winner or a tie. This should not be the case, ensure if the game is over the loop is terminated as well.

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name  (@mimipeshy) and I will be glad to help_
Regards
Peris Ndanu

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
